2024-06-07 15:26:25 | INFO | stdout | usage: controller.py [-h] [--host HOST] [--port PORT] [--dispatch-method {lottery,shortest_queue}] [--ssl]
2024-06-07 15:26:25 | INFO | stdout | 
2024-06-07 15:26:25 | INFO | stdout | options:
2024-06-07 15:26:25 | INFO | stdout |   -h, --help            show this help message and exit
2024-06-07 15:26:25 | INFO | stdout |   --host HOST
2024-06-07 15:26:25 | INFO | stdout |   --port PORT
2024-06-07 15:26:25 | INFO | stdout |   --dispatch-method {lottery,shortest_queue}
2024-06-07 15:26:25 | INFO | stdout |   --ssl                 Enable SSL. Requires OS Environment variables 'SSL_KEYFILE' and 'SSL_CERTFILE'.
2024-06-07 15:27:23 | INFO | controller | args: Namespace(host='0.0.0.0', port=21001, dispatch_method='shortest_queue', ssl=False)
2024-06-07 15:27:25 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m22852[0m]
2024-06-07 15:27:25 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-07 15:27:25 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-07 15:27:25 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:21001[0m (Press CTRL+C to quit)
2024-06-07 15:27:28 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-07 15:27:28 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-07 15:27:28 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-07 15:27:28 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m22852[0m]
2024-06-07 15:27:28 | ERROR | stderr | Traceback (most recent call last):
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-07 15:27:28 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-07 15:27:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-07 15:27:28 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-07 15:27:28 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-07 15:27:28 | ERROR | stderr | 
2024-06-07 15:27:28 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-07 15:27:28 | ERROR | stderr | 
2024-06-07 15:27:28 | ERROR | stderr | Traceback (most recent call last):
2024-06-07 15:27:28 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-07 15:27:28 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/FastChat/fastchat/serve/controller.py", line 389, in <module>
2024-06-07 15:27:28 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
2024-06-07 15:27:28 | ERROR | stderr |     server.run()
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
2024-06-07 15:27:28 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-07 15:27:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-07 15:27:28 | ERROR | stderr |     return runner.run(main)
2024-06-07 15:27:28 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-07 15:27:28 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 123, in run
2024-06-07 15:27:28 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-07 15:27:28 | ERROR | stderr | KeyboardInterrupt
2024-06-07 15:27:31 | ERROR | stderr | Exception ignored in: <module 'threading' from '/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/threading.py'>
2024-06-07 15:27:31 | ERROR | stderr | Traceback (most recent call last):
2024-06-07 15:27:31 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/threading.py", line 1622, in _shutdown
2024-06-07 15:27:31 | ERROR | stderr |     lock.acquire()
2024-06-07 15:27:31 | ERROR | stderr | KeyboardInterrupt:
