2024-06-07 15:59:38 | INFO | openai_api_server | args: Namespace(host='localhost', port=8000, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-07 15:59:38 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m46161[0m]
2024-06-07 15:59:38 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-06-07 15:59:38 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-06-07 15:59:38 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
2024-06-07 15:59:39 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-06-07 15:59:40 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-06-07 15:59:40 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-06-07 15:59:40 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m46161[0m]
2024-06-07 15:59:40 | ERROR | stderr | Traceback (most recent call last):
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 118, in run
2024-06-07 15:59:40 | ERROR | stderr |     return self._loop.run_until_complete(task)
2024-06-07 15:59:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-07 15:59:40 | ERROR | stderr |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-06-07 15:59:40 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-06-07 15:59:40 | ERROR | stderr | 
2024-06-07 15:59:40 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-07 15:59:40 | ERROR | stderr | 
2024-06-07 15:59:40 | ERROR | stderr | Traceback (most recent call last):
2024-06-07 15:59:40 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-07 15:59:40 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/FastChat/fastchat/serve/openai_api_server.py", line 939, in <module>
2024-06-07 15:59:40 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
2024-06-07 15:59:40 | ERROR | stderr |     server.run()
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
2024-06-07 15:59:40 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-06-07 15:59:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 194, in run
2024-06-07 15:59:40 | ERROR | stderr |     return runner.run(main)
2024-06-07 15:59:40 | ERROR | stderr |            ^^^^^^^^^^^^^^^^
2024-06-07 15:59:40 | ERROR | stderr |   File "/Users/suitongjian/anaconda3/envs/fschat/lib/python3.12/asyncio/runners.py", line 123, in run
2024-06-07 15:59:40 | ERROR | stderr |     raise KeyboardInterrupt()
2024-06-07 15:59:40 | ERROR | stderr | KeyboardInterrupt
